server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Chiefy22!
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

